### ISSUE TITLE
Container hangs after a ~20 seconds.

### ISSUE THREAD

**Issue by noetix** [jgillich/hyper-proxy#3]
Log:
```
> hyper-proxy@0.1.0 start /app
> node index.js

Killed
```

`hyper compose up -d -p lb`

`docker-compose.yml`:
```
version: '2'
services:
  proxy:
    image: jgillich/hyper-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - "HYPER_ACCESS=foo"
      - "HYPER_SECRET=bar"
    size: s3
    fip: 209.177.87.86
```

Debugging attempts:
- Tried using Lets Encrypt with the same result.
- Seems to work fine on local.
- Hyper account new and empty.
- Forked repo, enabled TLS DNS mode with Caddy, same result.
